# Generated by Django 3.0.1 on 2020-08-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCacheDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_id', models.CharField(max_length=255)),
                ('cache_duration', models.DateTimeField()),
                ('cache_value', models.TextField()),
            ],
        ),
    ]
