# Generated by Django 3.0.1 on 2020-08-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsNetParser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleCacheDB',
        ),
    ]
