# Generated by Django 3.1.3 on 2020-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAdmin', '0003_auto_20201114_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_sort',
            field=models.DateField(null=True),
        ),
    ]
