# Generated by Django 3.1.3 on 2021-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAdmin', '0005_auto_20201118_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date_posted', models.CharField(max_length=25)),
                ('content', models.TextField()),
            ],
        ),
    ]
