# Generated by Django 3.1.3 on 2021-01-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseAdmin', '0006_newsrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelease',
            name='ward',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
